mysql:
  container_name: ${MYSQL_CONTAINER}
  image: mysql:5.6
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
    - MYSQL_DATABASE=${DATABASE}
  ports:
    - 3333:3306
  volumes:
    - ./mysql/initdb:/docker-entrypoint-initdb.d
    - ./mysql/data:/var/lib/mysql

phpmyadmin:
  container_name: ${MYADMIN_CONTAINER}
  image: phpmyadmin/phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=password
  links:
    - mysql
  ports:
     - 8080:80
