mysql:
  container_name: ${MYSQL_CONTAINER}
  image: mysql:${MYSQL_VERSION}
  command: mysqld --character-set-server=${CHARASET} --collation-server=${COLLATION}
  environment:
    - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
    - MYSQL_USER={MYSQL_USER}
    - MYSQL_PASSWORD={MYSQL_PASSWORD}
    - MYSQL_DATABASE=${DATABASE}
  ports:
    - 3333:3306
  volumes:
    - ./mysql/initdb:/docker-entrypoint-initdb.d
    - ./mysql/data:/var/lib/mysql

phpmyadmin:
  container_name: ${MYADMIN_CONTAINER}
  image: phpmyadmin/phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD={MYSQL_ROOT_PASSWORD}
  links:
    - mysql
  ports:
     - 8080:80
